//! The bridge to the `ringframe` CLI.
//!
//! Weft never writes `.fab7/rf/` itself; every record goes through this CLI,
//! which validates, digests and refuses.
//! Everything here is a read or a question — Weft issues no write commands.

use std::path::Path;

use crate::outside::Outside;

use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The CLI is not installed. Weft still runs panes; it just has no record.
    NotInstalled,
    Refused {
        code: i32,
        message: String,
    },
}

fn run(out: &dyn Outside, project: &Path, args: &[&str]) -> Result<Vec<u8>, Error> {
    run_program(out, "ringframe", project, args)
}

/// "No CLI" and "the CLI said no" are different situations, so a spawn failure
/// becomes `NotInstalled` and never a refusal.
fn run_program(
    outside: &dyn Outside,
    program: &str,
    project: &Path,
    args: &[&str],
) -> Result<Vec<u8>, Error> {
    let project = project.to_string_lossy();
    let argv: Vec<&str> =
        ["--workspace", project.as_ref()].into_iter().chain(args.iter().copied()).collect();
    let out = outside.run(program, &argv, None).map_err(|_| Error::NotInstalled)?;
    if out.status.success() {
        return Ok(out.stdout);
    }
    // A refusal is said on stderr, or as JSON on stdout.
    let said = if out.stderr.is_empty() { &out.stdout } else { &out.stderr };
    Err(Error::Refused {
        code: out.status.code().unwrap_or(-1),
        message: String::from_utf8_lossy(said).trim().to_string(),
    })
}

fn json(out: &dyn Outside, project: &Path, args: &[&str]) -> Result<Value, Error> {
    let bytes = run(out, project, args)?;
    serde_json::from_slice(&bytes).map_err(|e| Error::Refused {
        code: 4,
        message: format!("could not read the CLI's answer: {e}"),
    })
}

/// RingFrame's own exit code for "refused by a rule", as its help documents.
const REFUSED_BY_A_RULE: i32 = 2;

/// Set the project up for RingFrame, as a person would with `ringframe init`.
/// A hook never makes the workspace; Weft does, through the CLI, before it
/// starts an agent whose hooks will record into it.
pub fn init(out: &dyn Outside, project: &Path) -> Result<(), Error> {
    run(out, project, &["init"]).map(|_| ())
}

pub fn installed(out: &dyn Outside) -> bool {
    out.run("ringframe", &["--version"], None).is_ok()
}

/// Whether this workspace could finish an Ask at all, asked of RingFrame.
///
/// `ask compile` has always refused a workspace with no Git repository or no
/// commit, but it runs at the end. Weft asks first, so `[A]SK` is dim with a
/// reason rather than typing an invocation that costs a turn and then fails.
pub fn ask_preflight(out: &dyn Outside, project: &Path) -> Result<(), Error> {
    match run(out, project, &["ask", "preflight"]) {
        Ok(_) => Ok(()),
        // Only a rule refusal is an answer. RingFrame documents its exit
        // codes: 1 is usage, which is what an older CLI says about a verb it
        // has never heard of, and that is not a statement about the
        // workspace. Weft stays quiet rather than inventing a problem.
        Err(Error::Refused { code, message }) if code == REFUSED_BY_A_RULE => {
            Err(Error::Refused { code, message })
        }
        Err(_) => Ok(()),
    }
}

/// The exact bytes to type. Never altered, never regenerated by Weft.
/// Record the person's yes for an Ask whose confirmation surface never got
/// one. RingFrame writes the record; Weft only carries the decision, which
/// the person made by pressing the key.
pub fn ask_confirm(out: &dyn Outside, project: &Path, ask_id: &str) -> Result<(), Error> {
    run(out, project, &["ask", "confirm", "--ask", ask_id]).map(|_| ())
}

/// The person submitted this Ask's prompt: Weft typed it on their yes and
/// pressed Enter. RingFrame records it as attributed to them; where a hook
/// also observes it arrive, that receipt outranks this.
pub fn ask_submitted(out: &dyn Outside, project: &Path, ask_id: &str) -> Result<(), Error> {
    run(out, project, &["ask", "submitted", "--ask", ask_id]).map(|_| ())
}

/// Open and gather the Eval of the open Asks, and say which it is: RingFrame
/// reads the change with Git and records it as gathered, so no harness has to
/// map it. An Eval already open over the same Asks and the same
/// work is the one to continue, and RingFrame names it.
pub fn eval_open(
    outside: &dyn Outside,
    project: &Path,
    agents: Option<&Value>,
    over: Option<&str>,
) -> Result<String, Error> {
    let agents = agents.map(Value::to_string);
    let mut args = vec!["eval", "open", "--host", "weft"];
    if let Some(a) = agents.as_deref() {
        args.extend(["--agents", a]);
    }
    if let Some(o) = over {
        args.extend(["--override", o]);
    }
    match json(outside, project, &args) {
        Ok(v) => {
            v.get("eval_id").and_then(Value::as_str).map(str::to_string).ok_or(Error::Refused {
                code: 4,
                message: "RingFrame opened an Eval and named none".into(),
            })
        }
        Err(Error::Refused { code, message }) => {
            let said: Value = serde_json::from_str(&message).unwrap_or(Value::Null);
            let detail = said.get("detail").and_then(Value::as_str).unwrap_or_default();
            if said.get("error").and_then(Value::as_str) == Some("eval.already_open")
                && let Some(id) = detail.split_whitespace().next().filter(|w| w.starts_with("evl_"))
            {
                return Ok(id.to_string());
            }
            let told = if detail.is_empty() { message } else { detail.to_string() };
            Err(Error::Refused { code, message: told })
        }
        Err(e) => Err(e),
    }
}

pub fn ask_copy(out: &dyn Outside, project: &Path, ask_id: &str) -> Result<Vec<u8>, Error> {
    run(out, project, &["ask", "copy", "--ask", ask_id])
}

/// How this harness's skills are invoked. Read from the profile rather than
/// assumed, because RingFrame owns the answer and it differs by host.
pub fn invocation_prefix(out: &dyn Outside, project: &Path, host: &str) -> Result<String, Error> {
    let v = json(out, project, &["profile", "show", "--host", host, "--json"])?;
    v.get("invocation_prefix")
        .and_then(Value::as_str)
        .map(str::to_string)
        .ok_or(Error::Refused { code: 4, message: "the profile names no invocation prefix".into() })
}

/// The size at which this host's composer folds a paste into a placeholder,
/// as the profile declares it.
///
/// Measured by RingFrame against the installed hosts and written down once, so
/// Weft reads it rather than carrying a second copy that can drift. `None`
/// means the profile does not say, and Weft then assumes nothing.
pub fn paste_fold_chars(out: &dyn Outside, project: &Path, host: &str) -> Option<usize> {
    let v = json(out, project, &["profile", "show", "--host", host, "--json"]).ok()?;
    v.get("paste_fold_chars").and_then(Value::as_u64).map(|n| n as usize)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Freshness {
    pub fresh: bool,
    pub subject_matches: bool,
}

/// Everything RingFrame says about a receipt when it re-verifies it. Exit 2
/// means "not fresh", not "broken", so the JSON is read whatever the code.
pub fn seal_checked(outside: &dyn Outside, project: &Path, seal_id: &str) -> Result<Value, Error> {
    let project = project.to_string_lossy();
    let args = ["--workspace", project.as_ref(), "seal", "check", "--seal", seal_id, "--json"];
    let out = outside.run("ringframe", &args, None).map_err(|_| Error::NotInstalled)?;
    serde_json::from_slice(&out.stdout).map_err(|_| Error::Refused {
        code: out.status.code().unwrap_or(-1),
        message: String::from_utf8_lossy(&out.stderr).trim().to_string(),
    })
}

/// A receipt a script can check.
pub fn seal_check(out: &dyn Outside, project: &Path, seal_id: &str) -> Result<Freshness, Error> {
    let v = seal_checked(out, project, seal_id)?;
    Ok(Freshness {
        fresh: v.get("fresh").and_then(Value::as_bool).unwrap_or(false),
        subject_matches: v.get("subject_matches").and_then(Value::as_bool).unwrap_or(false),
    })
}

/// What Weft types to start each step. The intent is appended for `ask`.
/// The invocation, with the space that closes it.
///
/// A harness offers completions while a skill token is still being typed, and
/// the first Enter after a bare token is taken by that chooser rather than
/// submitting: `$rf:eval` sat in a harness's composer, unsent, and Weft had no way
/// to tell. The trailing space ends the token, so Enter means send. Weft never
/// presses Enter twice to find out.
pub fn skill_command(prefix: &str, skill: &str) -> String {
    format!("{prefix}{skill} ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_skill_command_is_the_profiles_prefix_and_the_verb() {
        assert_eq!(skill_command("/rf:", "eval"), "/rf:eval ");
        assert_eq!(skill_command("$rf:", "ask"), "$rf:ask ");
    }

    #[test]
    fn a_bare_invocation_ends_with_the_space_that_closes_it() {
        // Found against Codex: the first Enter after a bare `$rf:eval` was
        // taken by the completion chooser, and the prompt sat there unsent.
        for skill in ["eval", "seal"] {
            assert!(skill_command("$rf:", skill).ends_with(' '), "{skill}");
        }
    }

    use crate::outside::Fixed;

    #[test]
    fn a_missing_cli_is_reported_as_missing_not_as_a_refusal() {
        let got = run_program(&Fixed::new(), "ringframe", Path::new("/tmp"), &["ask", "list"]);
        assert_eq!(got, Err(Error::NotInstalled));
        assert!(!installed(&Fixed::new()));
    }

    #[test]
    fn only_a_rule_refusal_is_an_answer_about_the_workspace() {
        // An older CLI answers a verb it does not know with a usage error
        // (exit 1). That says nothing about the workspace.
        let older = Fixed::new().answers("ringframe", &["ask", "preflight"], 1, "");
        assert!(ask_preflight(&older, Path::new("/p")).is_ok(), "a usage error is not a gap");
        let refused = Fixed::new().answers("ringframe", &["ask", "preflight"], 2, "no git");
        assert!(matches!(
            ask_preflight(&refused, Path::new("/p")),
            Err(Error::Refused { code: 2, .. })
        ));
    }

    #[test]
    fn the_prefix_is_the_profiles() {
        let world = Fixed::new().answers(
            "ringframe",
            &["profile", "show", "--host", "codex"],
            0,
            r#"{"invocation_prefix": "$rf:", "paste_fold_chars": 1001}"#,
        );
        assert_eq!(invocation_prefix(&world, Path::new("/p"), "codex"), Ok("$rf:".into()));
        assert_eq!(paste_fold_chars(&world, Path::new("/p"), "codex"), Some(1001));
    }

    #[test]
    fn an_unknown_host_degrades_rather_than_inventing_a_prefix() {
        let world = Fixed::new().exists("ringframe");
        let got = invocation_prefix(&world, Path::new("/p"), "not-a-harness");
        assert!(matches!(got, Err(Error::Refused { .. })), "{got:?}");
    }
}
