//! The bridge to the `ringframe` CLI.
//!
//! Spec: `plans/weft/spec/board.md`. Weft never writes `.fab7/rf/` itself;
//! every record goes through this CLI, which validates, digests and refuses.
//! Everything here is a read or a question — Weft issues no write commands.

use std::path::Path;
use std::process::Command;

use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The CLI is not installed. Weft still runs panes; it just has no record.
    NotInstalled,
    Refused {
        code: i32,
        message: String,
    },
}

fn run(project: &Path, args: &[&str]) -> Result<Vec<u8>, Error> {
    run_program("ringframe", project, args)
}

/// "No CLI" and "the CLI said no" are different situations, so a spawn failure
/// becomes `NotInstalled` and never a refusal.
fn run_program(program: &str, project: &Path, args: &[&str]) -> Result<Vec<u8>, Error> {
    let out = Command::new(program)
        .arg("--workspace")
        .arg(project)
        .args(args)
        .output()
        .map_err(|_| Error::NotInstalled)?;
    if out.status.success() {
        return Ok(out.stdout);
    }
    Err(Error::Refused {
        code: out.status.code().unwrap_or(-1),
        message: String::from_utf8_lossy(&out.stderr).trim().to_string(),
    })
}

fn json(project: &Path, args: &[&str]) -> Result<Value, Error> {
    let bytes = run(project, args)?;
    serde_json::from_slice(&bytes).map_err(|e| Error::Refused {
        code: 4,
        message: format!("could not read the CLI's answer: {e}"),
    })
}

/// RingFrame's own exit code for "refused by a rule", as its help documents.
const REFUSED_BY_A_RULE: i32 = 2;

pub fn installed() -> bool {
    Command::new("ringframe").arg("--version").output().is_ok()
}

/// Whether this workspace could finish an Ask at all, asked of RingFrame.
///
/// `ask compile` has always refused a workspace with no Git repository or no
/// commit, but it runs at the end. Weft asks first, so `[A]SK` is dim with a
/// reason rather than typing an invocation that costs a turn and then fails.
pub fn ask_preflight(project: &Path) -> Result<(), Error> {
    match run(project, &["ask", "preflight"]) {
        Ok(_) => Ok(()),
        // Only a rule refusal is an answer. RingFrame documents its exit
        // codes: 1 is usage, which is what an older CLI says about a verb it
        // has never heard of, and that is not a statement about the
        // workspace. Weft stays quiet rather than inventing a problem.
        Err(Error::Refused { code, message }) if code == REFUSED_BY_A_RULE => {
            Err(Error::Refused { code, message })
        }
        Err(_) => Ok(()),
    }
}

/// The exact bytes to type. Never altered, never regenerated by Weft.
/// Record the person's yes for an Ask whose confirmation surface never got
/// one. RingFrame writes the record; Weft only carries the decision, which
/// the person made by pressing the key.
pub fn ask_confirm(project: &Path, ask_id: &str) -> Result<(), Error> {
    run_program("ringframe", project, &["ask", "confirm", "--ask", ask_id]).map(|_| ())
}

pub fn ask_copy(project: &Path, ask_id: &str) -> Result<Vec<u8>, Error> {
    run(project, &["ask", "copy", "--ask", ask_id])
}

/// How this harness's skills are invoked. Read from the profile rather than
/// assumed, because RingFrame owns the answer and it differs by host.
pub fn invocation_prefix(project: &Path, host: &str) -> Result<String, Error> {
    let v = json(project, &["profile", "show", "--host", host, "--json"])?;
    v.get("invocation_prefix")
        .and_then(Value::as_str)
        .map(str::to_string)
        .ok_or(Error::Refused { code: 4, message: "the profile names no invocation prefix".into() })
}

/// The size at which this host's composer folds a paste into a placeholder,
/// as the profile declares it.
///
/// Measured by RingFrame against the installed hosts and written down once, so
/// Weft reads it rather than carrying a second copy that can drift. `None`
/// means the profile does not say, and Weft then assumes nothing.
pub fn paste_fold_chars(project: &Path, host: &str) -> Option<usize> {
    let v = json(project, &["profile", "show", "--host", host, "--json"]).ok()?;
    v.get("paste_fold_chars").and_then(Value::as_u64).map(|n| n as usize)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Freshness {
    pub fresh: bool,
    pub subject_matches: bool,
}

/// A receipt a script can check. Exit 2 means "not fresh", not "broken".
pub fn seal_check(project: &Path, seal_id: &str) -> Result<Freshness, Error> {
    let out = Command::new("ringframe")
        .arg("--workspace")
        .arg(project)
        .args(["seal", "check", "--seal", seal_id, "--json"])
        .output()
        .map_err(|_| Error::NotInstalled)?;
    let v: Value = serde_json::from_slice(&out.stdout).map_err(|_| Error::Refused {
        code: out.status.code().unwrap_or(-1),
        message: String::from_utf8_lossy(&out.stderr).trim().to_string(),
    })?;
    Ok(Freshness {
        fresh: v.get("fresh").and_then(Value::as_bool).unwrap_or(false),
        subject_matches: v.get("subject_matches").and_then(Value::as_bool).unwrap_or(false),
    })
}

/// What Weft types to start each step. The intent is appended for `ask`.
/// The invocation, with the space that closes it.
///
/// A harness offers completions while a skill token is still being typed, and
/// the first Enter after a bare token is taken by that chooser rather than
/// submitting: `$rf:eval` sat in Codex's composer, unsent, and Weft had no way
/// to tell. The trailing space ends the token, so Enter means send. Weft never
/// presses Enter twice to find out.
pub fn skill_command(prefix: &str, skill: &str) -> String {
    format!("{prefix}{skill} ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_skill_command_is_the_profiles_prefix_and_the_verb() {
        assert_eq!(skill_command("/rf:", "eval"), "/rf:eval ");
        assert_eq!(skill_command("$rf:", "ask"), "$rf:ask ");
    }

    #[test]
    fn a_bare_invocation_ends_with_the_space_that_closes_it() {
        // Found against Codex: the first Enter after a bare `$rf:eval` was
        // taken by the completion chooser, and the prompt sat there unsent.
        for skill in ["eval", "seal"] {
            assert!(skill_command("$rf:", skill).ends_with(' '), "{skill}");
        }
    }

    #[test]
    fn a_missing_cli_is_reported_as_missing_not_as_a_refusal() {
        let got =
            run_program("definitely-not-a-real-binary-weft", Path::new("/tmp"), &["ask", "list"]);
        assert_eq!(got, Err(Error::NotInstalled));
    }

    #[test]
    fn only_a_rule_refusal_is_an_answer_about_the_workspace() {
        // An older CLI answers "invalid choice" with exit 1. That says nothing
        // about the workspace, and Weft must not report it as though it did.
        if !installed() {
            eprintln!("skipped: ringframe is not on PATH");
            return;
        }
        let nowhere = Path::new("/");
        // Whatever this CLI makes of it, a usage error never blocks an Ask.
        // An older CLI answers a verb it does not know with a usage error.
        // Whatever this one makes of it, that is never a workspace gap.
        if let Err(Error::Refused { code: 1, .. }) = run(nowhere, &["ask", "preflight"]) {
            assert!(ask_preflight(nowhere).is_ok(), "a usage error is not a gap");
        }
    }

    #[test]
    fn the_cli_answers_where_it_is_installed() {
        if !installed() {
            eprintln!("skipped: ringframe is not on PATH");
            return;
        }
        let prefix = invocation_prefix(Path::new("/tmp"), "codex").expect("a profile");
        assert!(prefix.ends_with(':'), "a prefix ends at the verb: {prefix:?}");
    }

    #[test]
    fn an_unknown_host_degrades_rather_than_inventing_a_prefix() {
        if !installed() {
            eprintln!("skipped: ringframe is not on PATH");
            return;
        }
        let got = invocation_prefix(Path::new("/tmp"), "not-a-harness");
        assert!(got.is_ok() || matches!(got, Err(Error::Refused { .. })));
    }
}
