//! The bridge to the `ringframe` CLI.
//!
//! Spec: `plans/weft/spec/board.md`. Weft never writes `.fab7/rf/` itself;
//! every record goes through this CLI, which validates, digests and refuses.
//! Everything here is a read or a question — Weft issues no write commands.

use std::path::Path;
use std::process::Command;

use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The CLI is not installed. Weft still runs panes; it just has no record.
    NotInstalled,
    Refused { code: i32, message: String },
}

fn run(project: &Path, args: &[&str]) -> Result<Vec<u8>, Error> {
    let out = Command::new("ringframe")
        .arg("--workspace")
        .arg(project)
        .args(args)
        .output()
        .map_err(|_| Error::NotInstalled)?;
    if out.status.success() {
        return Ok(out.stdout);
    }
    Err(Error::Refused {
        code: out.status.code().unwrap_or(-1),
        message: String::from_utf8_lossy(&out.stderr).trim().to_string(),
    })
}

fn json(project: &Path, args: &[&str]) -> Result<Value, Error> {
    let bytes = run(project, args)?;
    serde_json::from_slice(&bytes).map_err(|e| Error::Refused {
        code: 4,
        message: format!("could not read the CLI's answer: {e}"),
    })
}

pub fn installed() -> bool {
    Command::new("ringframe").arg("--version").output().is_ok()
}

/// The exact bytes to type. Never altered, never regenerated by Weft.
pub fn ask_copy(project: &Path, ask_id: &str) -> Result<Vec<u8>, Error> {
    run(project, &["ask", "copy", "--ask", ask_id])
}

/// How this harness's skills are invoked. Read from the profile rather than
/// assumed, because RingFrame owns the answer and it differs by host.
pub fn invocation_prefix(project: &Path, host: &str) -> Result<String, Error> {
    let v = json(project, &["profile", "show", "--host", host, "--json"])?;
    v.get("invocation_prefix")
        .and_then(Value::as_str)
        .map(str::to_string)
        .ok_or(Error::Refused { code: 4, message: "the profile names no invocation prefix".into() })
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Freshness {
    pub fresh: bool,
    pub subject_matches: bool,
}

/// A receipt a script can check. Exit 2 means "not fresh", not "broken".
pub fn seal_check(project: &Path, seal_id: &str) -> Result<Freshness, Error> {
    let out = Command::new("ringframe")
        .arg("--workspace")
        .arg(project)
        .args(["seal", "check", "--seal", seal_id, "--json"])
        .output()
        .map_err(|_| Error::NotInstalled)?;
    let v: Value = serde_json::from_slice(&out.stdout).map_err(|_| Error::Refused {
        code: out.status.code().unwrap_or(-1),
        message: String::from_utf8_lossy(&out.stderr).trim().to_string(),
    })?;
    Ok(Freshness {
        fresh: v.get("fresh").and_then(Value::as_bool).unwrap_or(false),
        subject_matches: v.get("subject_matches").and_then(Value::as_bool).unwrap_or(false),
    })
}

/// What Weft types to start each step. The intent is appended for `ask`.
pub fn skill_command(prefix: &str, skill: &str) -> String {
    format!("{prefix}{skill}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_skill_command_is_the_profiles_prefix_and_the_verb() {
        assert_eq!(skill_command("/rf:", "eval"), "/rf:eval");
        assert_eq!(skill_command("$rf:", "ask"), "$rf:ask");
    }

    #[test]
    fn a_missing_cli_is_reported_as_missing_not_as_a_refusal() {
        // Resolved through PATH, so an empty PATH is the honest simulation.
        let out = Command::new("definitely-not-a-real-binary-weft").output();
        assert!(out.is_err(), "the fixture binary must not exist");
    }

    #[test]
    fn the_cli_answers_where_it_is_installed() {
        if !installed() {
            eprintln!("skipped: ringframe is not on PATH");
            return;
        }
        let prefix = invocation_prefix(Path::new("/tmp"), "codex").expect("a profile");
        assert!(prefix.ends_with(':'), "a prefix ends at the verb: {prefix:?}");
    }

    #[test]
    fn an_unknown_host_degrades_rather_than_inventing_a_prefix() {
        if !installed() {
            eprintln!("skipped: ringframe is not on PATH");
            return;
        }
        let got = invocation_prefix(Path::new("/tmp"), "not-a-harness");
        assert!(got.is_ok() || matches!(got, Err(Error::Refused { .. })));
    }
}
